// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAplOYgQEMdhtHibW6-iZdJ2RZG7FVehs0',
    appId: '1:769526006964:web:a54e91457427d7c12643e1',
    messagingSenderId: '769526006964',
    projectId: 'libbart-1e76f',
    authDomain: 'libbart-1e76f.firebaseapp.com',
    storageBucket: 'libbart-1e76f.appspot.com',
    measurementId: 'G-W0Q4LZ8DZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqkjAmv1_zqJt1yZeZCSeNKtGG4eu-iXk',
    appId: '1:769526006964:android:c51e87e3c56593022643e1',
    messagingSenderId: '769526006964',
    projectId: 'libbart-1e76f',
    storageBucket: 'libbart-1e76f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABppbdoHCsi2Ag8wnBj7MXH4go1t1KnJE',
    appId: '1:769526006964:ios:eb241bdf57aeaad92643e1',
    messagingSenderId: '769526006964',
    projectId: 'libbart-1e76f',
    storageBucket: 'libbart-1e76f.appspot.com',
    iosClientId: '769526006964-gjfjtgtktnpmmdu8a8a83c1l0a7o0guq.apps.googleusercontent.com',
    iosBundleId: 'com.example.libBart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABppbdoHCsi2Ag8wnBj7MXH4go1t1KnJE',
    appId: '1:769526006964:ios:eb241bdf57aeaad92643e1',
    messagingSenderId: '769526006964',
    projectId: 'libbart-1e76f',
    storageBucket: 'libbart-1e76f.appspot.com',
    iosClientId: '769526006964-gjfjtgtktnpmmdu8a8a83c1l0a7o0guq.apps.googleusercontent.com',
    iosBundleId: 'com.example.libBart',
  );
}
